Tron:
  apiKey: 

Db:
  host: 127.0.0.1
  dbName: yj
  userName: root
  password: root

Node:
  ethereum: https://sepolia.infura.io/v3/
  bsc: https://data-seed-prebsc-1-s1.binance.org:8545/
  tron: grpc.nile.trongrid.io:50051

#Node:
#  ethereum: https://eth.llamarpc.com
#  bsc: https://bsc-dataseed1.defibit.io
#  tron: grpc.trongrid.io:50051


Inform:
  url: http://127.0.0.1:2025/api/informReceive


System:
  port: 2025
  router: http://127.0.0.1
